### ISSUE TITLE
(test, Vietnam) Backfill

### ISSUE THREAD

**Issue by Rouein** [owid/covid-19-data#2380] opened 2022-01-31 12:20 UTC
Manual backfill is needed. The link in the [script](https://github.com/owid/covid-19-data/pull/2379) can provide the source.

**Comment by Rouein** [comment] 2022-01-31 12:25
#2379

**Comment by edomt** [comment] 2022-01-31 12:37
Duplicate of #2379

**Closed by edomt** 2022-01-31 12:37 UTC

**Comment by Rouein** [comment] 2022-01-31 12:41
Perhaps reopening it after merging. The script is incremental, it only adds the data of the last update. Historical data should be recovered manually.

**Comment by edomt** [comment] 2022-01-31 12:48
We have all the historical data in our testing data already (https://github.com/owid/covid-19-data/blob/master/public/data/testing/covid-testing-all-observations.csv)

**Comment by Rouein** [comment] 2022-01-31 13:09
Great I was not aware of it, Vietnam sheet was not in [automation folder](https://github.com/owid/covid-19-data/tree/master/scripts/scripts/testing/automated_sheets).
Do you input manually collected data directly to public?

**Comment by lucasrodes** [comment] 2022-01-31 13:42
That is correct @Rouein,
Manual updates currently go directly to `public` without passing through the `scripts` folder. This however may change with ongoing the ongoing refactor #2099
