### ISSUE TITLE
Saudi Arabia Numbers

### ISSUE THREAD

**Issue by msgoussi** [owid/covid-19-data#1601] opened 2021-06-24 06:16 UTC
I have lot of friends in Saudi Arabia and they are fully vacanicated. 
However your data shows otherwise.
Please advise.

**Comment by lucasrodes** [comment] 2021-06-24 09:48
Hi @msgoussi,
Thanks for your message.

Closing this issue because I am unsure of what the issue is. We report official numbers from https://covid19.moh.gov.sa.

Feel free to reopen.

**Closed by lucasrodes** 2021-06-24 09:48 UTC
