### ISSUE TITLE
Recovered and active cases

### ISSUE THREAD

**Issue by abitrolly** [owid/covid-19-data#2] opened 2020-03-24 15:54 UTC
It will be useful to get graph of people who are currently infected. There are stats on deaths and cases, but unfortunately, no data on those who recovered.

**Comment by HannahRitchie** [comment] 2020-03-25 17:03
Our current data source on this is the European CDC (https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide) which do not currently provide figures on recoveries.

For now we will focus on confirmed cases and deaths, but may think about extending this work in the future.

**Comment by abitrolly** [comment] 2020-03-26 13:51
It would still be nice to see several data sources for cross-checking? I have no idea where all these institutions get the data from my county, because there is official data publication source even for citizens.

**Comment by javierconcha** [comment] 2020-05-05 22:46
I came here while looking at the visualization tool on this page:
https://www.visualcapitalist.com/infection-trajectory-flattening-the-covid19-curve/
First, thanks for the great work. 
Second, I agree with @abitrolly about having recovered case, as a way to infer active cases (active =total-recovered-deaths), and not only cumulative data, would be very useful. 
I would argue that to show the active cases time series would make a better case in order to understand the "flattening the curve" concept as the typical figure showed to the general public to explain this concept is active cases and not cumulative cases. I am referring to this curve (also shown in linked I mentioned at the beginning):
[Flattening the curve figure](https://en.wikipedia.org/wiki/Flatten_the_curve#/media/File:20200403_Flatten_the_curve_animated_GIF.gif)
Lastly, I tried to find a visualization tool like the one used in the first link I mentioned but for active cases, and surprisingly I did not find any. Therefore, a similar visualization for active cases would make this repo even more relevant.

**Comment by lcocea** [comment] 2020-09-04 20:21
I support the comments and requests above. Would you please consider adding a new column to the daily OWID data set to include "Active cases per million"? This data can be obtained by subtracting 'recovered' and 'deaths' from 'confirmed' cases (three separate tables available at https://data.humdata.org/dataset/novel-coronavirus-2019-ncov-cases ). Thank you.

**Comment by pegasone** [comment] 2020-09-24 16:53
For those looking for code to parse active cases from the JHU data sets: [JHUData.cs](https://github.com/pegasone/cov2con/blob/master/code/JHUData.cs)

**Comment by abitrolly** [comment] 2020-09-25 12:16
@pegasone by making it in Python you can submit a PR.

**Comment by Toxyl** [comment] 2020-09-29 21:37
> For those looking for code to parse active cases from the JHU data sets: [JHUData.cs](https://github.com/pegasone/cov2con/blob/master/code/JHUData.cs)
> This C# file is part of the COV2CON project on GitHub.

Problem is that most countries do not provide data or only incomplete data (e.g. Belgium did have recovery data during the first wave but nowadays there seems to be no new data). In the end I went with the inference as suggested by @javierconcha and plotted that over the provided data where available, for quite a few countries that have recovery data it looks like they calculated it in a similar fashion. So I stopped using the JHU recovery data and went with my own estimation.

**Comment by pegasone** [comment] 2020-09-29 22:12
This is a plot of Belgium recovered data (per JHU data set) as of today, 2020-09-29. Where is the part where there is no data? 

![belgium_recovered_jhu_2020-09-29](https://user-images.githubusercontent.com/20741937/94621982-4b28cf80-027f-11eb-8515-146990265f25.png)

Anyway, however incomplete, I think the first step is obtaining the reported data; in the absence of reported data, any extrapolation or inference is speculative.

**Comment by pegasone** [comment] 2020-10-02 04:25
"Cases" actually and unfortunatelly means PCR-positive cases. These may continue to increase until potentially all the population is tested. Therefore, I am not surprised to see  "active cases" increasing with time at this stage. As a "positive" individual is not necessarily sick (i.e., has no signs and symptoms), IMO this molecular testing is a poor choice for reporting on the COVID-19 status in a region, because it drives important decisions such as when and where to initiate lockdowns, quarantines etc. If only patients presenting with COVID-19 signs and symptoms were reported as confirmed cases then I would agree with your rationale.

**Comment by Toxyl** [comment] 2020-10-02 05:41
@pegasone What you are referring to is called "confirmed" in the JHU dataset. Which is not the same as **active** cases. And at least here in the Netherlands there wasn't much testing in the beginning, only individuals with COVID-19 signs were tested and therefore only those appeared in the "confirmed" data of the JHU. And this should probably apply to most other countries because all of them first had to get hold of enough tests before they could start testing people without signs of infections.

To get definitions straight: an active case is someone who at the given point in time has the disease. Which consequentially means that that active case has to disappear from the record after 2-6 weeks because they have either recovered or died. And this is not effected by whether a case is asymptomatic or not, as asymptomatic cases also recover from it. Following this definition it not logical for active cases to only increase because that would imply that infected people never recover.

And yes, I know that the disease technically can take longer than 2 weeks, but that isn't easily accounted for without actual recovery data. Furthermore, a part of the incubation period has already passed when someone appears as a confirmed case in the data, i.e. my estimate of roughly 13 days is the time **after** the case has been reported, so before I consider an infected individual recovered or dead about 3-4 weeks since infection have passed. And like I said, it is an estimate, which I have purely based on the average duration of the disease and *visually* matching the curve to deaths, overall infections (when they [almost] plateau you can assume that people must have started getting better 1-2 weeks prior) and, where available, recovery data.

**Comment by abitrolly** [comment] 2020-10-05 05:50
To calculate currently infected people worldwide (active cases), the only data what is needed is the daily new cases and daily deaths.
```
active = sum(daily_new[today - 2.weeks: today])
```
Recoveries and deaths come with a 2 weeks gap relative to active cases.
```
deaths = daily_deaths[today - 2.weeks: today]
recoveries = daily_new[today - 4.weeks: today - 2.weeks] - deaths
```

**Comment by edomt** [comment] 2020-12-22 09:50
I'll close this issue, as there is no reliable method to calculate recovered/active cases for all countries (and no aggregated data source that makes this data available).

**Closed by edomt** 2020-12-22 09:50 UTC
Labels: cases, enhancement
