### ISSUE TITLE
US data per state?

### ISSUE THREAD

**Issue by Bejoscha** [owid/covid-19-data#116] opened 2020-07-27 13:04 UTC
Is there any chance of getting a split-down of the values for the US per state instead of having it all lumped together?

**Comment by edomt** [comment] 2020-07-29 20:58
Hi @Bejoscha 

See #31: for now our plan is to stick to country-level data, as we don't currently have the time or resources to delve into local or regional data. However, I can point you to the COVID Tracking Project and [its great API](https://covidtracking.com/api), which should have everything you need.

However, I'll keep this issue to keep track of requests about this, in case we do decide to dedicate resources to this in the future.

Ed

**Comment by edomt** [comment] 2021-01-20 09:16
Closing this: we now have state-level data for vaccination: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv

And for other metrics this is a duplicate of #193

**Closed by edomt** 2021-01-20 09:16 UTC
Labels: cases, deaths, enhancement, tests
