### ISSUE TITLE
Unfortunately this is not what the new data represents. You can click on the "i" button so:

### ISSUE THREAD

**Issue by Naty1209** [owid/covid-19-data#2366] opened 2022-01-29 12:58 UTC
Unfortunately this is not what the new data represents. You can click on the "i" button so:
![image](https://user-images.githubusercontent.com/445416/151660819-cdbd778d-a068-4bf0-8a95-cc0e11dd0d89.png)
This roughly translate to this:
"The daily change in the number of patients with COVID-19 virus hospitalized in hospitals in each of the 3 medical conditions: mild, moderate and severe (including critical)
The daily figure shows the number of patients according to their new medical condition if they were previously defined in another medical condition".
summing the three states does not give you daily new hospitalizations, but a larger number, including people who's condition got better (say from severe to mild).

_Originally posted by @yuval-harpaz in https://github.com/owid/covid-19-data/issues/2330#issuecomment-1024901938_

**Comment by edomt** [comment] 2022-01-29 13:26
duplicate of #2366

**Closed by edomt** 2022-01-29 13:26 UTC
